name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
    secrets:
      registery_username:
        required: true
      registery_password:
        required: true
        
        
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Registery
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.registery_username}}
          password: ${{secrets.registery_password}}
          
      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then 
            echo "final_tag=latest" >> $GITHUB_ENV
          else 
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
          
#       - name: Build and Push the Image 
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           push: true
#           tags: ${{secrets.registery_username}}/${{inputs.image_name}}:${{env.final_tag}}
          
  do-something-else:
    needs: builds
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
            
      
      
      
