name: Check_test

on:
  push:
    branches: [ master, dev ]
    paths:
      - '**/src/main/**'
      - '**/src/test/**'
      - '.github/workflows/checkstyle-and-license-check.yml'
      - 'examples/shardingsphere-example-generator/**'
      - '!examples/**'
      - '!*.md'
  pull_request:
    branches: [ master ]
    paths:
      - '**/src/main/**'
      - '**/src/test/**'
      - '.github/workflows/checkstyle-and-license-check.yml'
      - 'examples/shardingsphere-example-generator/**'
      - '!examples/**'
      - '!*.md'

concurrency:
  group: check-${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-checkstyle:
    name: Check - checkstyle
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: shardingsphere-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run checkstyle
        run: ./mvnw checkstyle:check -T1C
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: shardingsphere-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
     


  check-license:
    name: Check - license
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: apache/skywalking-eyes@v0.4.0
